package com.mycompany.gerenciamentoempresa;

public class TelaCadastroProduto extends javax.swing.JInternalFrame {

    private boolean editando = false;
    private Produto produto = new Produto();
    /**
     * Creates new form TelaCadastroProduto
     */
    public TelaCadastroProduto() {
        initComponents();
    }
    
    public TelaCadastroProduto(boolean editando, Produto produto) {
        initComponents();
        
        this.editando = editando;
        this.produto = produto;
        
        jTextNome.setText(produto.getNome());
        jTextQtd.setText(String.valueOf(produto.getQuantidade()));
        jTextValor.setText(String.valueOf(produto.getValor()));
        jTextDesc.setText(produto.getDescricao());
        jTextCodCategoria.setText(String.valueOf(produto.getCodigoCategoria()));
        jTextCodFilial.setText(String.valueOf(produto.getCodigoFilial()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextQtd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextDesc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextCodCategoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextCodFilial = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Produto");

        jLabel2.setText("Nome:");

        jLabel3.setText("Quantidade:");

        jLabel4.setText("Valor:");

        jLabel5.setText("Descrição:");

        jLabel6.setText("Código Categoria:");

        jLabel7.setText("Código da Filial:");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(12, 12, 12)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jTextNome)
                        .addComponent(jTextQtd)
                        .addComponent(jTextValor)
                        .addComponent(jTextDesc)
                        .addComponent(jTextCodCategoria)
                        .addComponent(jTextCodFilial, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jTextQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jTextValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(jTextDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(jTextCodCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(jTextCodFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ProdutoDAO produtoBanco = new ProdutoDAO();
        
        produto.setNome(jTextNome.getText());
        produto.setQuantidade(Integer.parseInt(jTextQtd.getText()));
        produto.setValor(Double.parseDouble(jTextValor.getText()));
        produto.setDescricao(jTextDesc.getText());
        produto.setCodigoCategoria(Integer.parseInt(jTextCodCategoria.getText()));
        produto.setCodigoFilial(Integer.parseInt(jTextCodFilial.getText()));
        
        if (!editando) {
            produtoBanco.adicionarProduto(produto);
        } else {
            produtoBanco.atualizarProduto(produto);
        }
        
        jTextNome.setText("");
        jTextQtd.setText("");
        jTextValor.setText("");
        jTextDesc.setText("");
        jTextCodCategoria.setText("");
        jTextCodFilial.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextCodCategoria;
    private javax.swing.JTextField jTextCodFilial;
    private javax.swing.JTextField jTextDesc;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextQtd;
    private javax.swing.JTextField jTextValor;
    // End of variables declaration//GEN-END:variables
}
